Update user profile and display for other users and nonexistent user
Capstone-G3/Foraging-Tracker pull request #31
Opened 2024-10-28 20:01 UTC by flickin4

Other users can be accessed thru id passed into url, if user does not exist it will display the default page where username is set to "Nonexistent User". I also updated the appbar so clicking on username will bring user to the user page, added appbar to page, and updated some styling and values.
Currently I am only looping through user's markers and displaying a grey box for each, since Jenny is currently working on the Home Feed and I'm not sure how we want to display that information yet.
![image](https://github.com/user-attachments/assets/76cc3065-af16-42e4-b74f-11b49115d4cb)
![image](https://github.com/user-attachments/assets/48e5706a-7bb2-458d-aaf9-6a23e72524b5)
![image](https://github.com/user-attachments/assets/1f4f9af6-4906-4573-b65f-50923615870f)

2024-10-29 20:06 UTC, DeHampster approved these changes
looks great!

2024-10-30 00:00 UTC, danzzu requested changes
If possible make revision for readability and these ifs could cause side-effect flaws.

2024-10-30 00:00 UTC, danzzu commented on foraging_app/templates/base.html
> +                    <a href="{% url 'user' %}"><span class="username-text">{{ user.username }}</span></a>
Doesn't user url need an argument userID?

2024-10-30 00:00 UTC, danzzu commented on foraging_app/views/user.py
> +    def get(self, request, userId = None):
If the user requested the page user/<some id> then userId parameter should never be default to None and always contain a value of url GET request.

2024-10-30 00:00 UTC, danzzu commented on foraging_app/views/user.py
> +        if (userId == None):
Given that userID is always in the request, if checking for if it is personal account just compare the current request.user.id and the userID (from the url). If it is then it's personal otherwise not.

2024-10-31 00:57 UTC, danzzu approved these changes
Awesome work!

2024-10-31 01:40 UTC, ivangit546 approved these changes
looks good

2024-10-31 02:23 UTC, merged